export const simple = {
  basic: {
    outline: "none",
    padding: 6,
    "font-size": 13,
    "font-weight": "bold",
    color: "f7f7f7",
    "background-color": "40a7de",
    "border-style": "none",
    "border-radius": 4,
    "transition-duration": 3,
  },
  basicShadows: [0, 1, 6, 0, { r: 0, g: 0, b: 0 }, 29],
  hover: {
    outline: "none",
    padding: 6,
    "font-size": 13,
    "font-weight": "bold",
    color: "ffffff",
    "background-color": "17a1eb",
    "border-style": "none",
    "border-radius": 4,
    "transition-duration": 3,
  },
  hoverShadows: [0, 1, 7, 0, { r: 0, g: 0, b: 0 }, 41],
  active: {
    outline: "none",
    padding: 6,
    "font-size": 13,
    "font-weight": "bold",
    color: "ffffff",
    "background-color": "0087cf",
    "border-style": "none",
    "border-radius": 4,
    "transition-duration": 1,
  },
  activeShadows: [0, 0, 6, 0, { r: 0, g: 0, b: 0 }, 51],
};

export const bordered = {
  basic: {
    outline: "none",
    padding: 6,
    "font-size": 12,
    "font-weight": "bold",
    color: "005ff7",
    "background-color": "ffffff",
    "border-style": "solid",
    "border-radius": 4,
    "transition-duration": 2,
    "border-color": "9cb1f0",
  },
  basicShadows: [0, 0, 0, 0, { r: 0, g: 0, b: 0 }, 100],
  hover: {
    outline: "none",
    padding: 6,
    "font-size": 13,
    "font-weight": "bold",
    color: "0037ff",
    "background-color": "ffffff",
    "border-style": "solid",
    "border-radius": 4,
    "transition-duration": 1,
    "border-color": "456de6",
  },
  hoverShadows: [0, 0, 1, 0, { r: 0, g: 0, b: 0 }, 11],
  active: {
    outline: "none",
    padding: 6,
    "font-size": 12,
    "font-weight": "bold",
    color: "0041b0",
    "background-color": "ffffff",
    "border-style": "solid",
    "border-radius": 4,
    "border-width": 1,
    "transition-duration": 1,
    "border-color": "9cb1f0",
  },
  activeShadows: [0, 0, 0, 0, { r: 0, g: 0, b: 0 }, 100],
};

export const rounded = {
  basic: {
    outline: "none",
    padding: 11,
    "font-weight": "bold",
    color: "dade00",
    "background-color": "852eff",
    "border-style": "none",
    "border-radius": 21,
    "transition-duration": 3,
  },
  basicShadows: [0, 2, 4, 1, { r: 0, g: 0, b: 0 }, 46],
  hover: {
    outline: "none",
    padding: 11,
    "font-weight": "bold",
    color: "fbff03",
    "background-color": "9857f2",
    "border-style": "none",
    "border-radius": 21,
    "transition-duration": 3,
  },
  hoverShadows: [0, 3, 5, 2, { r: 0, g: 0, b: 0 }, 50],
  active: {
    outline: "none",
    padding: 11,
    "font-weight": "bold",
    color: "ab11ed",
    "background-color": "e8d100",
    "border-style": "none",
    "border-radius": 21,
    "transition-duration": 1,
  },
  activeShadows: [0, 1, 3, 1, { r: 0, g: 0, b: 0 }, 69],
};

export const round = {
  basic: {
    outline: "none",
    width: 70,
    height: 70,
    "border-style": "none",
    "border-radius": 50,
    "font-weight": "bold",
    "font-size": 17,
    color: "ebebeb",
    "background-color": "cf1010",
    "transition-duration": 3,
  },
  basicShadows: [1, 2, 4, 1, { r: 0, g: 0, b: 0 }, 48],
  hover: {
    outline: "none",
    width: 75,
    height: 75,
    "border-style": "none",
    "border-radius": 50,
    "font-weight": "bold",
    "font-size": 19,
    color: "f5f5f5",
    "background-color": "e80909",
    "transition-duration": 1,
  },
  hoverShadows: [1, 8, 20, 1, { r: 0, g: 0, b: 0 }, 36],
  active: {
    outline: "none",
    width: 60,
    height: 60,
    "border-style": "none",
    "border-radius": 50,
    "font-weight": "normal",
    "font-size": 14,
    color: "ffffff",
    "background-color": "ff0303",
    "transition-duration": 0,
  },
  activeShadows: [0, 1, 3, 1, { r: 0, g: 0, b: 0 }, 68],
};
